### PR TITLE
Added the ability to download chat transcript as .srt (subtitles) file

### PR DESCRIPTION
**Pull request by Rubenxx00**
Hi, I added a radio button to download chat transcript as an .srt file, compatible by default with most video players.

### CODE REVIEW

**Comment by jacopo-j** [comment]
Hi, I thought about doing this in the past, but it breaks when recordings are paused and then resumed. After the pause the subtitles go out of sync because the difference between the absolute time of the comment and the start of the recording changes. Does your solution deal with this?

**Comment by Rubenxx00** [comment]
Unfortunately it doesn't, I didn't think about it. I'm afraid we can't find any info about this...
So it only works with some lessons, sorry.

**Comment by jacopo-j** [comment]
Then I would be inclined not to merge this PR. I understand that some may find it "better than nothing" but having a feature that only works sometimes might be more confusing than beneficial. People who are interested can always switch to your fork. I hope you agree

**Comment by Rubenxx00** [comment]
👍

**Pull request closed without merging**
